auth_server:
  rpc:
    host: 'localhost'
    port: 9999
  auth_file: '/home/xxli/repository/dataflow-demo/auth.yml'

data_server:
  rpc:
    host: 'localhost'
    port: 10000
  mysql:
    host: 'localhost'
    port: 3306
    user: 'zhuoshi'
    password: 'zhuoshi'
    databases:
      - stock_tick
      - futures_tick
      - index_tick
  mongodb:
    host: 'localhost'
    port: 27017
    databases:
      - market_daily:
        name:
          market_daily
        collections:
          - stock
          - futures
          - index
      - model:
        name: model
        collections:
          - signal

signal_service:
  rpc:
    host: 'localhost'
    port: 10001
  data_server_auth:
    user: 'signal_service'
    password: 'signal_service'
