rpc:
  host: 'localhost'
  port: 10000

data_server:
  mysql:
    host: 'localhost'
    port: 3306
    user: 'zhuoshi'
    password: 'zhuoshi'
    databases:
      - stock_tick
      - futures_tick
      - index_tick
  mongodb:
    host: 'localhost'
    port: 27017
    databases:
      - market_daily:
        name:
          market_daily
        collections:
          - stock
          - futures
          - index
