# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signal.proto',
  package='signal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0csignal.proto\x12\x06signal\"\x1d\n\rSignalRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x0bSignalReply\x12\x0b\n\x03sig\x18\x01 \x01(\x02\x32\x44\n\x06Signal\x12:\n\nCalcSignal\x12\x15.signal.SignalRequest\x1a\x13.signal.SignalReply\"\x00\x62\x06proto3'
)




_SIGNALREQUEST = _descriptor.Descriptor(
  name='SignalRequest',
  full_name='signal.SignalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='signal.SignalRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_SIGNALREPLY = _descriptor.Descriptor(
  name='SignalReply',
  full_name='signal.SignalReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sig', full_name='signal.SignalReply.sig', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['SignalRequest'] = _SIGNALREQUEST
DESCRIPTOR.message_types_by_name['SignalReply'] = _SIGNALREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignalRequest = _reflection.GeneratedProtocolMessageType('SignalRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALREQUEST,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.SignalRequest)
  })
_sym_db.RegisterMessage(SignalRequest)

SignalReply = _reflection.GeneratedProtocolMessageType('SignalReply', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALREPLY,
  '__module__' : 'signal_pb2'
  # @@protoc_insertion_point(class_scope:signal.SignalReply)
  })
_sym_db.RegisterMessage(SignalReply)



_SIGNAL = _descriptor.ServiceDescriptor(
  name='Signal',
  full_name='signal.Signal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=83,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalcSignal',
    full_name='signal.Signal.CalcSignal',
    index=0,
    containing_service=None,
    input_type=_SIGNALREQUEST,
    output_type=_SIGNALREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNAL)

DESCRIPTOR.services_by_name['Signal'] = _SIGNAL

# @@protoc_insertion_point(module_scope)
