# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import signal_pb2 as signal__pb2


class SignalStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalcSignal = channel.unary_unary(
                '/signal.Signal/CalcSignal',
                request_serializer=signal__pb2.SignalRequest.SerializeToString,
                response_deserializer=signal__pb2.SignalReply.FromString,
                )


class SignalServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CalcSignal(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalcSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcSignal,
                    request_deserializer=signal__pb2.SignalRequest.FromString,
                    response_serializer=signal__pb2.SignalReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signal.Signal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Signal(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CalcSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signal.Signal/CalcSignal',
            signal__pb2.SignalRequest.SerializeToString,
            signal__pb2.SignalReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
